### ISSUE TITLE
Big stream splitted into partial chunks crash 

### ISSUE THREAD

**Issue by josacar** [nukeproof/oanda_api#18]
Given a partial `chunk` of a bigger response, this leads into crash.

Consider this first chunk:

```
"{\"tick\":{\"instrument\":\"AUD_CAD\",\"time\":\"2018-01-05T21:59:59.473927Z\",\"bid\":0.97521,\"ask\":0.97671}}\r\n{\"tick\":{\"instrument\":\"AUD_CHF\",\"time\":\"2018-01-05T21:59:59.474077Z\",\"bid\":0.76571,\"ask\":0.76736}}\r\n{\"tick\":{\"instrument\":\"AUD_HKD\",\"time\":\"2018-01-05T21:59:59.474684Z\",\"bid\":6.14378,\"ask\":6.15161}}\r\n{\"tick\":{\"instrument\":\"AUD_JPY\",\"time\":\"2018-01-05T21:59:59.475339Z\",\"bid\":88.825,\"ask\":88.975}}\r\n{\"tick\":{\"instrument\":\"AUD_NZD\",\"time\":\"2018-01-05T21:59:59.475615Z\",\"bid\":1.09594,\"ask\":1.09794}}\r\n{\"tick\":{\"instrument\":\"AUD_SGD\",\"time\":\"2018-01-05T21:59:59.476296Z\",\"bid\":1.04193,\"ask\":1.04457}}\r\n{\"tick\":{\"instrument\":\"AUD_USD\",\"time\":\"2018-01-05T21:59:59.476933Z\",\"bid\":0.78588,\"ask\":0.78668}}\r\n{\"tick\":{\"instrument\":\"CAD_CHF\",\"time\":\"2018-01-05T21:59:59.502941Z\",\"bid\":0.78465,\"ask\":0.78624}}\r\n{\"tick\":{\"instrument\":\"CAD_HKD\",\"time\":\"2018-01-05T21:59:59.503520Z\",\"bid\":6.29577,\"ask\":6.30297}}\r\n{\"tick\":{\"instrument\":\"CAD_JPY\",\"time\":\"2018-01-05T21:59:59.504483Z\",\"bid\":90.985,\"ask\":91.158}}\r\n{\"tick\":{\"instrument\":\"CAD_SGD\",\"time\":\"2018-01-05T21:59:59.505022Z\",\"bid\":1.06765,\"ask\":1.07021}}\r\n{\"tick\":{\"instrument\":\"CHF_HKD\",\"time\":\"2018-01-05T21:59:59.507817Z\",\"bid\":8.01454,\"ask\":8.02565}}\r\n{\"tick\":{\"instrument\":\"CHF_JPY\",\"time\":\"2018-01-05T21:59:59.508422Z\",\"bid\":115.895,\"ask\":116.095}}\r\n{\"tick\":{\"instrument\":\"CHF_ZAR\",\"time\":\"2018-01-05T21:59:59.509617Z\",\"bid\":12.58124,\"ask\":12.67149}}\r\n{\"tick\":{\"instrument\":\"EUR_AUD\",\"time\":\"2018-"
```

```
"01-05T21:59:59.517293Z\",\"bid\":1.52897,\"ask\":1.53097}}\r\n{\"tick\":{\"instrument\":\"EUR_CAD\",\"time\":\"2018-01-05T21:59:59.517199Z\",\"bid\":1.49259,\"ask\":1.49409}}\r\n{\"tick\":{\"instrument\":\"EUR_CHF\",\"time\":\"2018-01-05T21:59:59.517229Z\",\"bid\":1.17189,\"ask\":1.17299}}\r\n{\"tick\":{\"instrument\":\"EUR_CZK\",\"time\":\"2018-01-05T21:59:59.517965Z\",\"bid\":25.48221,\"ask\":25.58221}}\r\n{\"tick\":{\"instrument\":\"EUR_DKK\",\"time\":\"2018-01-05T21:59:59.518078Z\",\"bid\":7.44555,\"ask\":7.4482}}\r\n{\"tick\":{\"instrument\":\"EUR_GBP\",\"time\":\"2018-01-05T21:59:59.518234Z\",\"bid\":0.88618,\"ask\":0.88718}}\r\n{\"tick\":{\"instrument\":\"EUR_HKD\",\"time\":\"2018-01-05T21:59:59.518062Z\",\"bid\":9.40212,\"ask\":9.40922}}\r\n{\"tick\":{\"instrument\":\"EUR_HUF\",\"time\":\"2018-01-05T21:59:59.518262Z\",\"bid\":307.937,\"ask\":308.939}}\r\n{\"tick\":{\"instrument\":\"EUR_JPY\",\"time\":\"2018-01-05T21:59:59.518365Z\",\"bid\":135.963,\"ask\":136.063}}\r\n{\"tick\":{\"instrument\":\"EUR_NOK\",\"time\":\"2018-01-05T21:59:59.518926Z\",\"bid\":9.66865,\"ask\":9.69905}}\r\n{\"tick\":{\"instrument\":\"EUR_NZD\",\"time\":\"2018-01-05T21:59:59.519076Z\",\"bid\":1.67748,\"ask\":1.67948}}\r\n{\"tick\":{\"instrument\":\"EUR_PLN\",\"time\":\"2018-01-05T21:59:59.519232Z\",\"bid\":4.14709,\"ask\":4.15655}}\r\n{\"tick\":{\"instrument\":\"EUR_SEK\",\"time\":\"2018-01-05T21:59:59.519330Z\",\"bid\":9.79215,\"ask\":9.83265}}\r\n{\"tick\":{\"instrument\":\"EUR_SGD\",\"time\":\"2018-01-05T21:59:59.519423Z\",\"bid\":1.59444,\"ask\":1.59765}}\r\n{\"tick\":{\"instrument\":\"EUR_TRY\",\"time\":\"2018-01-05T21:59:59.519618Z\",\"bid\":4.48425,\"ask\":4.5"
```

This ends crashing:

```
/usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/time.rb:302:in `utc': argument out of range (ArgumentError)
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/time.rb:302:in `make_time'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/time.rb:370:in `parse'
	from /Users/selu/code/oanda_api/lib/oanda_api/resource/price.rb:12:in `time='
	from /Users/selu/code/oanda_api/lib/oanda_api/resource_base.rb:89:in `block in initialize_attributes'
	from /Users/selu/code/oanda_api/lib/oanda_api/resource_base.rb:88:in `each'
	from /Users/selu/code/oanda_api/lib/oanda_api/resource_base.rb:88:in `initialize_attributes'
	from /Users/selu/code/oanda_api/lib/oanda_api/resource_base.rb:20:in `initialize'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:127:in `new'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:127:in `block in handle_response'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:122:in `map'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:122:in `handle_response'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:97:in `block (2 levels) in stream'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/protocol.rb:429:in `call_block'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/protocol.rb:420:in `<<'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/protocol.rb:122:in `read'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http/response.rb:321:in `read_chunked'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http/response.rb:285:in `block in read_body_0'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http/response.rb:278:in `inflater'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http/response.rb:283:in `read_body_0'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http/response.rb:204:in `read_body'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:93:in `block in stream'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http.rb:1455:in `block in transport_request'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http/response.rb:165:in `reading_body'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http.rb:1454:in `transport_request'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http.rb:1416:in `request'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /usr/local/opt/asdf/installs/ruby/2.4.3/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/request.rb:92:in `stream'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/client.rb:136:in `block in execute_request'
	from /Users/selu/code/tmp/vendor/bundle/ruby/2.4.0/gems/http-exceptions-0.1.1/lib/http/exceptions.rb:38:in `block in wrap_and_check'
	from /Users/selu/code/tmp/vendor/bundle/ruby/2.4.0/gems/http-exceptions-0.1.1/lib/http/exceptions.rb:25:in `wrap_exception'
	from /Users/selu/code/tmp/vendor/bundle/ruby/2.4.0/gems/http-exceptions-0.1.1/lib/http/exceptions.rb:37:in `wrap_and_check'
	from /Users/selu/code/oanda_api/lib/oanda_api/streaming/client.rb:130:in `execute_request'
	from /Users/selu/code/oanda_api/lib/oanda_api/client/namespace_proxy.rb:107:in `method_missing'
	from oanda.rb:13:in `<main>'
```

**Comment by nukeproof** [comment]
Thanks @josacar. I'll merge this pr when I finish #20.

**Comment by josacar** [comment]
Appreciated @nukeproof

**Comment by josacar** [comment]
More info about this bug with current master:

Using latest master I get this:

```
oanda_subscriber.rb:28: Tracking 23: ["eur/eur", "eur/usd", "eur/jpy", "eur/gbp", "gbp/usd", "usd/jpy", "usd/sgd", "usd/mxn", "usd/try", "usd/hkd", "usd/sar", "usd/cad", "aud
/usd", "usd/chf", "nzd/usd", "usd/zar", "usd/usd", "usd/krw", "usd/inr", "eur/bhd", "usd/bhd", "usd/vnd", "usd/brl"] currencies.
currency_pair.rb:69: 1516700025 - 2018-01-23 09:33:45 +0000 - EUR/USD - 1.22361
currency_pair.rb:69: 1516700026 - 2018-01-23 09:33:46 +0000 - EUR/JPY - 135.469
currency_pair.rb:69: 1516700018 - 2018-01-23 09:33:38 +0000 - EUR/GBP - 0.87716
currency_pair.rb:69: 1516700021 - 2018-01-23 09:33:41 +0000 - GBP/USD - 1.395
currency_pair.rb:69: 1516700005 - 2018-01-23 09:33:25 +0000 - USD/JPY - 110.7105
currency_pair.rb:69: 1516700007 - 2018-01-23 09:33:27 +0000 - USD/SGD - 1.32039
currency_pair.rb:69: 1516700029 - 2018-01-23 09:33:49 +0000 - USD/MXN - 18.74904
currency_pair.rb:69: 1516700028 - 2018-01-23 09:33:48 +0000 - USD/TRY - 3.79249
currency_pair.rb:69: 1516700002 - 2018-01-23 09:33:22 +0000 - USD/HKD - 7.81748
currency_pair.rb:69: 1516699877 - 2018-01-23 09:31:17 +0000 - USD/SAR - 3.75018
currency_pair.rb:69: 1516700029 - 2018-01-23 09:33:49 +0000 - USD/CAD - 1.24765
currency_pair.rb:69: 1516700024 - 2018-01-23 09:33:44 +0000 - AUD/USD - 0.79635
currency_pair.rb:69: 1516699957 - 2018-01-23 09:32:37 +0000 - USD/CHF - 0.96327
oanda_subscriber.rb:10: The session has expired we die!
log.rb:20: [SAFELY] Type: Yajl::ParseError
log.rb:21: [SAFELY] Message: parse error: after key and value, inside map, I expect ',' or '}'
                                        {"tick":{"instrument":"EUR_USD
                     (right here) ------^
log.rb:22: [SAFELY] Backtrace: /home/vagrant/bundler/2.4.2/ruby/2.4.0/bundler/gems/oanda_api-9f43e26ee391/lib/oanda_api/streaming/adapters/yajl.rb:17:in `parse'
  /home/vagrant/bundler/2.4.2/ruby/2.4.0/bundler/gems/oanda_api-9f43e26ee391/lib/oanda_api/streaming/adapters/yajl.rb:17:in `parse'
  /home/vagrant/bundler/2.4.2/ruby/2.4.0/bundler/gems/oanda_api-9f43e26ee391/lib/oanda_api/streaming/request.rb:140:in `parse'
  /home/vagrant/bundler/2.4.2/ruby/2.4.0/bundler/gems/oanda_api-9f43e26ee391/lib/oanda_api/streaming/request.rb:121:in `handle_response'
  /home/vagrant/bundler/2.4.2/ruby/2.4.0/bundler/gems/oanda_api-9f43e26ee391/lib/oanda_api/streaming/request.rb:96:in `block (2 levels) in stream'
```

With my proposal I get this:

```
oanda_subscriber.rb:28: Tracking 23: ["eur/eur", "eur/usd", "eur/jpy", "eur/gbp", "gbp/usd", "usd/jpy", "usd/sgd", "usd/mxn", "usd/try", "usd/hkd", "usd/sar", "usd/cad", "aud
/usd", "usd/chf", "nzd/usd", "usd/zar", "usd/usd", "usd/krw", "usd/inr", "eur/bhd", "usd/bhd", "usd/vnd", "usd/brl"] currencies.
currency_pair.rb:69: 1516700176 - 2018-01-23 09:36:16 +0000 - EUR/USD - 1.22396
currency_pair.rb:69: 1516700179 - 2018-01-23 09:36:19 +0000 - EUR/JPY - 135.513
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - EUR/GBP - 0.87728
currency_pair.rb:69: 1516700175 - 2018-01-23 09:36:15 +0000 - GBP/USD - 1.39519
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - USD/JPY - 110.7165
currency_pair.rb:69: 1516700179 - 2018-01-23 09:36:19 +0000 - USD/SGD - 1.3202
currency_pair.rb:69: 1516700177 - 2018-01-23 09:36:17 +0000 - USD/MXN - 18.73489
currency_pair.rb:69: 1516700178 - 2018-01-23 09:36:18 +0000 - USD/TRY - 3.79026
currency_pair.rb:69: 1516700128 - 2018-01-23 09:35:28 +0000 - USD/HKD - 7.81753
currency_pair.rb:69: 1516699877 - 2018-01-23 09:31:17 +0000 - USD/SAR - 3.75018
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - USD/CAD - 1.24748
currency_pair.rb:69: 1516700168 - 2018-01-23 09:36:08 +0000 - AUD/USD - 0.79661
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - USD/CHF - 0.96317
currency_pair.rb:69: 1516700179 - 2018-01-23 09:36:19 +0000 - NZD/USD - 0.73209
currency_pair.rb:69: 1516700176 - 2018-01-23 09:36:16 +0000 - EUR/USD - 1.22396
currency_pair.rb:69: 1516700179 - 2018-01-23 09:36:19 +0000 - EUR/JPY - 135.513
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - EUR/GBP - 0.87728
currency_pair.rb:69: 1516700175 - 2018-01-23 09:36:15 +0000 - GBP/USD - 1.39519
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - USD/JPY - 110.7165
currency_pair.rb:69: 1516700179 - 2018-01-23 09:36:19 +0000 - USD/SGD - 1.3202
currency_pair.rb:69: 1516700177 - 2018-01-23 09:36:17 +0000 - USD/MXN - 18.73489
currency_pair.rb:69: 1516700178 - 2018-01-23 09:36:18 +0000 - USD/TRY - 3.79026
currency_pair.rb:69: 1516700128 - 2018-01-23 09:35:28 +0000 - USD/HKD - 7.81753
currency_pair.rb:69: 1516699877 - 2018-01-23 09:31:17 +0000 - USD/SAR - 3.75018
currency_pair.rb:69: 1516700182 - 2018-01-23 09:36:22 +0000 - USD/CAD - 1.24748
currency_pair.rb:69: 1516700168 - 2018-01-23 09:36:08 +0000 - AUD/USD - 0.79661
```

The problem here is when reassembling chunks in chunked reponse, as the chunks in streaming requests are always ended by `\r\n`. This is a live example:

```
CHUNK: {"tick":{"instrument":"EUR_USD","time":"2018-01-23T09:39:39.536427Z","bid":1.22418,"ask":1.22428}}
```

```
CHUNK: }
{"tick":{"instrument":"USD_ZAR","time":"2018-01-23T09:39:40.997729Z","bid":12.0871,"ask":12.09662}}
```

```
CHUNK:
```

```
CHUNK: {"tick":{"instrument":"USD_HKD","time":"2018-01-23T09:39:41.397167Z","bid":7.81744,"ask":7.81782}}
{"tick":{"instrument":"USD_HKD","time":"2018-01-23T09:39:41.398971Z","bid":7.81742,"ask":7.8178}}
```

As you can see `streamed chunks` can be in different  chunks of the `read_body` response. 

The ideal thing would be detecting the `streaming chunks` in the `read_body chunks` as they are different. We can simplify by `\r\n\Z`, but the ideal would be parsing the `read_body chunk` until `\r\n` without minding if it's in the middle or not, so we get a `streaming chunk`.

**Comment by josacar** [comment]
Proposing another solution:

```ruby
def stream(&block)
  @stop_requested = false
  @running = true
  # @http.set_debug_output $stderr
  r, w = IO.pipe
  @http.request(@request) do |response|
    response.read_body do |chunk|
      w << chunk

      handle_response(r.gets("\r\n")).each do |resource|
        block.call(resource, @client)
        return if stop_requested?
      end

      return if stop_requested?
      sleep 0.01
    end
  end
ensure
  @running = false
  @http.finish if @http.started?
end
```

but this crashes a lot of tests as it yields one by one in the request, maybe we have to change them.

Also I'm experiencing some freezes with the `IO.pipe` approach after some minutes.
